### ISSUE TITLE
image preview

### ISSUE THREAD

**Issue by marefati110** [willnguyen1312/zoom-image#191]
### Description of the problem

It would be great if there was a feature to preview images

like https://www.npmjs.com/package/react-awesome-lightbox

**Comment by willnguyen1312** [comment]
Hi, @marefati110, thanks for your feedback. The feature to preview images is very nice. Yet, it is not the project's goal since UI is the most challenging part and it is impossible to provide ones unless we have a particular spec for it like Material Design or Ant Design. The core design of Zoom Image is inspired by the [TanStack](https://tanstack.com/) project. By mainly focusing on the logic from the library side, it creates unlimited capacity for UI customization from an application standpoint - The sky is the limit :)

As you can see from react-awesome-lightbox, it has its own [style file](https://github.com/theanam/react-awesome-lightbox/blob/master/build/style.css). This might work for someone but not others, it leads to more or less CSS override shipped to browsers to customize the look and feel of applications. It also adds extra weight to bundle size which is bad for performance

I hope the answer above is clear enough to explain the ultimate goal of the project. I also updated the README and projection documentation site to reflect your feedback 🙂

Thanks so much

Best,
Nam

**Comment by willnguyen1312** [comment]
Hi Ali, I am going to close the issue since it's inactive for a while. Please feel free to open up if you need further discussion. Thanks so much :)
