### ISSUE TITLE
Don't harvest my e-mail address to send me spam

### ISSUE THREAD

**Issue by jonhermansen** [willnguyen1312/zoom-image#193]
### Describe the bug

Please don't be an asshole on the internet.

I never signed up for your "mailing list".

Don't harvest people's e-mail addresses just so you can promote your project.

Thanks.

### Reproduction

https://github.com/willnguyen1312/zoom-image

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/willnguyen1312/zoom-image/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is available

**Comment by willnguyen1312** [comment]
Dear @jonhermansen,

I really am sorry to make you feel that way. It is never my intention to make you feel like that. I started my journey as a software engineer seven years ago. I have learned from others to collect interest from other repositories and share the work I have done with them. I have received emails from others asking for my feedback back in the day and I did. I thought it's time for me to do the same thing. I also advocate the library on Twitter via hashtags [buildInPublic](https://twitter.com/buildinpublic?lang=en). You could notice from my Github contribution graph that I just started my journey a few months ago. I wanted to join open-source after many years of taking advantage of it at work to fulfill my job. So far, I have made friends with many great developers across the globe. Some of them have given me great feedback to make the library better over time to benefit the community. Others even asked for making integration into their library. The experience I have received so far is very positive :)

Again, I deeply apologize to make you feel so :)

Best,
Nam

**Comment by jonhermansen** [comment]
OK, maybe I overreacted a bit. You're not the first one to harvest my e-mail from GitHub, so I apologize if I responded in a disproportionate way -- I am mostly frustrated that e-mail harvesting is being done, not mad at you specifically.

For future reference, you should refer to [GitHub's Acceptable Use Policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies). It clearly states:

> You may not use information from the Service (whether scraped, collected through our API, or obtained otherwise) for spamming purposes, including for the purposes of sending unsolicited emails to users or selling personal information, such as to recruiters, headhunters, and job boards.

If you're in the US, you may also be subject to laws that protect my (and your!) personal information. If you're operating in the US, there is the [CAN-SPAM act](https://en.wikipedia.org/wiki/CAN-SPAM_Act_of_2003). In California, there's also the CCPA and CPRA, which protect consumers' personally identifiable information. And if you're in the EU, you may also be subject to the GDPR. I am not a lawyer but I do believe that these laws are meant to protect people's right to privacy and from unfettered access to their personal information (including an e-mail address).

Dude, I get it. You're just trying to promote your project. I've also done some work in open source myself, and I understand the drive you have to find a good fit for your project, find people that it will be helpful for, and get the word out that you're building something useful. I don't think your project is stupid, but it's a bit frustrating on my end to receive e-mail I've not consented to, that I never specifically gave my address to you for marketing purposes, and to top it all off, I had no way to opt-out of receiving future e-mails.

Again, I apologize for the crude tone earlier, but I really wanted to get my point across that I did NOT consent to receiving the message. I meant no harm to you either.

I wish you, your family, and your project the best in the future.

**Comment by willnguyen1312** [comment]
Dear Jon,

Thanks so much for your understanding @jonhermansen. I am originally from Vietnam and new to everything in North America - I just arrived in Canada back in March. Thanks so much for teaching me a valuable lesson today. And, I will never be truly happy knowing that good people like you feel bad... Again, I'm so sorry for not being aware of that... ☺️

I am going to do it the right way to make sure everyone is happy and benefits from the work of open-source enthusiasts like us - via pull request and open discussion. I have worked on a library called [headlessmedia](https://willnguyen1312.github.io/headlessplayback) to help UI libraries integrate with other famous streaming libraries like hls.js and dash.js - I think I will open pull requests in those libraries to ask the authors whether it's okay to list it in their projects 🙂

As you could see from my Github profile page, everything is publicly available. I have worked and developed several internal solutions for several companies. I found it good, scalable and wanted to share with the world plus make it better. I'm very happy to make some friends along the way as I mentioned above... I am just so sorry about making guys like you feel bad due to my ignorance... Thanks for letting me know Jon, I truly appreciated ❤️ 

Thanks a lot for your wishes. I wish you and your beloved ones well and happiness 💖

Best,
Nam
