### ISSUE TITLE
Demos broken

### ISSUE THREAD

**Issue by bfalchuk** [willnguyen1312/zoom-image#41]
Hi, looking forward to testing and trying but the demos are currently broken.

**Comment by willnguyen1312** [comment]
Hi @bfalchuk, thanks so much for your interest in this. I am sorry for the inconvenience you had. Could you please provide me with the link to the broken demo? And which browser did you use?

Typically, the demo should work like this.
![demo](https://github.com/willnguyen1312/zoom-image/assets/17794897/75cd79bc-1a33-4e06-8a93-6be117a7cd30)

The screen might be too small. You could try to adjust the embedded editor or open the demo in a dedicated editor tab which is powered by Codesandbox - Open Editor button
<img width="1172" alt="image" src="https://github.com/willnguyen1312/zoom-image/assets/17794897/e0810d3a-dcbe-4531-9860-9a05f9f9cebf">


Thanks so much 🙂

**Comment by bfalchuk** [comment]
So sorry, my mistake; corporate VPN access issue (somehow part of the page was blocked). Closing.

**Comment by ChetSocio** [comment]
> Hi, looking forward to testing and trying but the demos are currently broken.

Hey do you know how can i make images zoom on hover bu default without showing buttons and forcing users to click in order to acheive zoom on hover? Why the autor of this package has forced us to click in order to achieve zoom on hover? When i set { name: "Hover", href: "#", current: true, value: "hover" }, directly, i get `Failed to execute removeChild` error always, This package is kinda irritating me now. How can we acheieve same as react-image-zoom ??
